### ISSUE TITLE
Missing label row

### ISSUE THREAD

**Issue by thanhlecongg** [SophieHYe/ODSExperiment#2]
Hi, 
I am trying run your RQ1 Experiment, but, the path './data/ase2020.csv' is not available. So I try to replace it by https://github.com/SophieHYe/ODSExperiment/blob/main/Experiment/data/ASE20-902-Patches.csv
However, I found that your ASE20-902-Patches seem to be missing the first row, which contains the field of each column. 
I wonder if you can update them.
Thank you so much.

**Comment by SophieHYe** [comment]
The labels have been updated! Thanks!
