### ISSUE TITLE
Different versions of libraries lead to different results on PatchSIM dataset

### ISSUE THREAD

**Issue by thanhlecongg** [SophieHYe/ODSExperiment#3]
Dear the authors,
While we use the your original source code with the newest version of libraries, we got the following error:
```
AttributeError                           
Traceback (most recent call last)
/home/hungnh/Thanh/TSE_submission/ODSExperiment/Experiment/RQ2-PatchSim-Comparison_old.ipynb Cell 13 in <cell line: 4>()
      [2](vscode-notebook-cell://ssh-remote%2Bdslab/home/hungnh/Thanh/TSE_submission/ODSExperiment/Experiment/RQ2-PatchSim-Comparison_old.ipynb#X15sdnNjb2RlLXJlbW90ZQ%3D%3D?line=1) from sklearn.model_selection import train_test_split, RandomizedSearchCV
      [3](vscode-notebook-cell://ssh-remote%2Bdslab/home/hungnh/Thanh/TSE_submission/ODSExperiment/Experiment/RQ2-PatchSim-Comparison_old.ipynb#X15sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2) smote = SMOTE(random_state=42,sampling_strategy='minority')
----> [4](vscode-notebook-cell://ssh-remote%2Bdslab/home/hungnh/Thanh/TSE_submission/ODSExperiment/Experiment/RQ2-PatchSim-Comparison_old.ipynb#X15sdnNjb2RlLXJlbW90ZQ%3D%3D?line=3) X_train, Y_train = smote.fit_sample(X_train, Y_train)

AttributeError: 'SMOTE' object has no attribute 'fit_sample'
```

To adress this issue, we followed this [post](https://stackoverflow.com/questions/66364406/attributeerror-smote-object-has-no-attribute-fit-sample) and change fit_sample() to fit_resample() as the function fit_sample() is [decrepted from imbalance v0.4](https://imbalanced-learn.org/stable/whats_new.html?fbclid=IwAR2ScdsD8yhS4PU5D8wnUMJKuguoiuQj1v9-Rpf2se69HGMSvwgTCrWC7vs#version-0-4). 

However, we got different results compared to the original results, which are reported in the paper. For example, we obtain 31 TP and 8 FP while in the paper the correspoding numbers are 35 and 4. We guess that the difference come from the version of imbalance and function sample().

I wonder if you can provide the specific version of libraries (not only imbalance) that ODS used for us to replicate the reported results.
Many thanks. I am looking forward to hearing from you.

**Comment by SophieHYe** [comment]
Dear Thanh,
As we discussed via email, please try the new 4000+ crossed features in ODS to build the new training model. Thanks :)
